#include "tiny_compiler.h"

extern int num_globals;
extern int next_array_base;

void compile(const char* source) {
    init_lexer(source);
    current_token = get_next_token();

    ASTNode* ast = program();
    generate_program(ast);

    printf("Generated bytecode (%d instructions)\n", code_buffer.size);
    print_bytecode(code_buffer.code, code_buffer.size);

    printf("\n--- Program Output ---\n");
    run_vm(code_buffer.code, code_buffer.size, num_globals, next_array_base);
    printf("----------------------\n");
}

void print_bytecode(Instruction* code, int size) {
    for (int i = 0; i < size; i++) {
        printf("%4d: ", i);
        switch (code[i].op) {
            case OP_PUSH: printf("PUSH %d\n", code[i].operand); break;
            case OP_POP: printf("POP\n"); break;
            case OP_STORE: printf("STORE %d\n", code[i].operand); break;
            case OP_LOAD: printf("LOAD %d\n", code[i].operand); break;
            case OP_ADD: printf("ADD\n"); break;
            case OP_SUB: printf("SUB\n"); break;
            case OP_MUL: printf("MUL\n"); break;
            case OP_DIV: printf("DIV\n"); break;
            case OP_MOD: printf("MOD\n"); break;
            case OP_EQ: printf("EQ\n"); break;
            case OP_NE: printf("NE\n"); break;
            case OP_LT: printf("LT\n"); break;
            case OP_LTE: printf("LTE\n"); break;
            case OP_GT: printf("GT\n"); break;
            case OP_GTE: printf("GTE\n"); break;
            case OP_AND: printf("AND\n"); break;
            case OP_OR: printf("OR\n"); break;
            case OP_NOT: printf("NOT\n"); break;
            case OP_NEG: printf("NEG\n"); break;
            case OP_JMP: printf("JMP %d\n", code[i].operand); break;
            case OP_JMP_IF: printf("JMP_IF %d\n", code[i].operand); break;
            case OP_CALL: printf("CALL %s\n", (char*)code[i].operand); break;
            case OP_RET: printf("RET\n"); break;
            case OP_PRINT: printf("PRINT\n"); break;
            case OP_PRINT_STR: printf("PRINT_STR %s\n", (char*)code[i].operand); break;
            case OP_ARRAY_LOAD: printf("ARRAY_LOAD\n"); break;
            case OP_ARRAY_STORE: printf("ARRAY_STORE\n"); break;
            case OP_HALT: printf("HALT\n"); break;
            default: printf("UNKNOWN\n");
        }
    }
}

// Test programs for each new feature

const char* test_arrays() {
    return
        "func main() {"
        "   var arr: int[5];"
        "   arr[0] = 42;"
        "   arr[1] = 100;"
        "   arr[2] = arr[0] + arr[1];"
        "   print(arr[0]);"
        "   print(\" + \");"
        "   print(arr[1]);"
        "   print(\" = \");"
        "   print(arr[2]);"
        "   print(\"\\n\");"
        "}";
}

const char* test_for_loop() {
    return
        "func main() {"
        "   var sum: int = 0;"
        "   for (var i: int = 1; i <= 10; i = i + 1) {"
        "       sum = sum + i;"
        "   }"
        "   print(\"Sum 1..10 = \");"
        "   print(sum);"
        "   print(\"\\n\");"
        "}";
}

const char* test_logical_ops() {
    return
        "func main() {"
        "   var a: int = 5;"
        "   var b: int = 10;"
        "   if (a > 0 && b > 0) {"
        "       print(\"Both positive\\n\");"
        "   }"
        "   if (a > 100 || b > 5) {"
        "       print(\"At least one condition holds\\n\");"
        "   }"
        "   var flag: bool = true;"
        "   if (!flag) {"
        "       print(\"Should not print\\n\");"
        "   }"
        "   print(\"Logical ops test done\\n\");"
        "}";
}

const char* test_break_continue() {
    return
        "func main() {"
        "   print(\"Break at 7: \");"
        "   var i: int = 0;"
        "   while (i < 10) {"
        "       i = i + 1;"
        "       if (i == 7) { break; }"
        "       print(i);"
        "       print(\" \");"
        "   }"
        "   print(\"\\n\");"
        "}";
}

const char* test_continue_demo() {
    return
        "func main() {"
        "   print(\"Skip 3: \");"
        "   var i: int = 0;"
        "   while (i < 7) {"
        "       i = i + 1;"
        "       if (i == 3) { continue; }"
        "       print(i);"
        "       print(\" \");"
        "   }"
        "   print(\"\\n\");"
        "}";
}

const char* test_modulo() {
    return
        "func main() {"
        "   var a: int = 17;"
        "   var b: int = 5;"
        "   print(\"17 % 5 = \");"
        "   print(a % b);"
        "   print(\"\\n\");"
        "   print(\"10 % 3 = \");"
        "   print(10 % 3);"
        "   print(\"\\n\");"
        "   print(\"7 % 2 = \");"
        "   print(7 % 2);"
        "   print(\"\\n\");"
        "}";
}

const char* test_for_with_break() {
    return
        "func main() {"
        "   var sum: int = 0;"
        "   for (var i: int = 1; i <= 100; i = i + 1) {"
        "       if (i > 5) { break; }"
        "       sum = sum + i;"
        "   }"
        "   print(\"Sum 1..5 (for+break) = \");"
        "   print(sum);"
        "   print(\"\\n\");"
        "}";
}

const char* test_nested_loops() {
    return
        "func main() {"
        "   print(\"Nested loops:\\n\");"
        "   var i: int = 0;"
        "   while (i < 3) {"
        "       i = i + 1;"
        "       var j: int = 0;"
        "       while (j < 3) {"
        "           j = j + 1;"
        "           if (j == 2) { continue; }"
        "           print(i);"
        "           print(\",\");"
        "           print(j);"
        "           print(\" \");"
        "       }"
        "       print(\"\\n\");"
        "   }"
        "}";
}

const char* test_else_if() {
    return
        "func main() {"
        "   var score: int = 75;"
        "   if (score >= 90) {"
        "       print(\"A\\n\");"
        "   } else if (score >= 80) {"
        "       print(\"B\\n\");"
        "   } else if (score >= 70) {"
        "       print(\"C\\n\");"
        "   } else {"
        "       print(\"F\\n\");"
        "   }"
        "}";
}

const char* test_original() {
    return
        "func main() {"
        "   var x: int = 42;"
        "   var y: int = 100;"
        "   if (x < y) {"
        "       print(\"x is less than y, value: \");"
        "       print(x);"
        "   }"
        "   print(\"\\n\");"
        "   var i: int = 0;"
        "   while (i < 5) {"
        "       print(\"Loop: \");"
        "       print(i);"
        "       print(\"\\n\");"
        "       i = i + 1;"
        "   }"
        "}";
}

int main() {
    printf("========================================\n");
    printf(" HW3: Extended TinyLang Compiler Tests\n");
    printf("========================================\n");

    printf("\n\n--- Test 1: Arrays ---\n");
    compile(test_arrays());

    printf("\n\n--- Test 2: For Loop ---\n");
    compile(test_for_loop());

    printf("\n\n--- Test 3: Logical Operators (&&, ||, !) ---\n");
    compile(test_logical_ops());

    printf("\n\n--- Test 4: Break ---\n");
    compile(test_break_continue());

    printf("\n\n--- Test 5: Continue ---\n");
    compile(test_continue_demo());

    printf("\n\n--- Test 6: Modulo (%) ---\n");
    compile(test_modulo());

    printf("\n\n--- Test 7: For Loop + Break ---\n");
    compile(test_for_with_break());

    printf("\n\n--- Test 8: Nested Loops + Continue ---\n");
    compile(test_nested_loops());

    printf("\n\n--- Test 9: Else-If ---\n");
    compile(test_else_if());

    printf("\n\n--- Test 10: Original HW2 Features ---\n");
    compile(test_original());

    return 0;
}